//AUTHORIZED
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_INFO = 'UPDATE_INFO';

//MODAL

export const SIGNUP_MODAL_ON = 'SIGNUP_MODAL_ON';
export const SIGNIN_MODAL_ON = 'SIGNIN_MODAL_ON';
export const CREATE_GATHER_ROOM_MODAL_ON ='CREATE_GATHER_ROOM_MODAL_ON';
export const CREATE_GATHER_ROOM_DETAIL_MODAL_ON ='CREATE_GATHER_ROOM_DETAIL_MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

//GATH
export const SEARCH_GATHER = 'SEARCH_GATHER'
