export const testdumState= () => {
    return [
    {
        "id":1,
        "email":"gschiell0@scientificamerican.com",
        "password":"2IniK0W7",
        "username":"odwyer0"
        },
     {
         "id":2,
         "email":"mgorrissen1@zimbio.com",
         "password":"K2OwtxB2",
         "username":"dblanshard1"
        },
     {
         "id":3,
         "email":"hoda2@addtoany.com",
         "password":"Uc6JXDPBvNN9",
         "username":"choldin2"
        },
     {
         "id":4,
         "email":"jpithcock3@ox.ac.uk",
         "password":"6afDrYvtYHNN",
         "username":"wslay3"
        },
     {
         "id":5,
         "email":"sdulwich4@example.com",
         "password":"ihVIdQ8",
         "username":"sboni4"
        },
     {
         "id":6,
         "email":"iricht5@netlog.com",
         "password":"cG1x30rUPp",
         "username":"baddeycott5"
        },
     {
         "id":7,
         "email":"dmannin6@businessinsider.com",
         "password":"8zyC73yF3Wk",
         "username":"asiward6"
        },
     {
         "id":8,
         "email":"gforrester7@cbc.ca",
         "password":"CdpU3cR",
         "username":"nbartak7"
        },
     {
         "id":9,
         "email":"tmacparlan8@cdc.gov",
         "password":"0ncv1r",
         "username":"amcdermott8"
        },
     {
         "id":10,
         "email":"dglide9@yolasite.com",
         "password":"Rf0V4VJF",
         "username":"eberndt9"
        }
     ]}